name: pipeline CI

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Création de la bdd
        run: python data/create_db.py

      - name: lancement des tests
        run: pytest tests/ -v --cov=app --cov-report=html --cov-report=term --cov-fail-under=75

      - name: artefact rapport html
        uses: actions/upload-artifact@v4
        with:
          name: html-cov
          path: htmlcov/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/christophe-ringot/Oc_P5 hf-space
          rsync -av --exclude='hf-space' --exclude='.git' --exclude='assets/img/diagramme.png' --exclude='.env' --exclude='.env.local' . hf-space/
          cd hf-space
          git lfs install
          git lfs track "*.joblib"
          git add .gitattributes
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes"
          git push
